//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationsTester.VariableHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class CanadianCredentials : global::System.Configuration.ApplicationSettingsBase {
        
        private static CanadianCredentials defaultInstance = ((CanadianCredentials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CanadianCredentials())));
        
        public static CanadianCredentials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800000001892")]
        public string XWebIDCredit {
            get {
                return ((string)(this["XWebIDCredit"]));
            }
            set {
                this["XWebIDCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6lm2JTrHoBWldO6eaoRnqDBZVXDgKAG1")]
        public string XWebAuthKeyCredit {
            get {
                return ((string)(this["XWebAuthKeyCredit"]));
            }
            set {
                this["XWebAuthKeyCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80022813")]
        public string XWebTerminalIDCredit {
            get {
                return ((string)(this["XWebTerminalIDCredit"]));
            }
            set {
                this["XWebTerminalIDCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800000001892")]
        public string XWebIDDebit {
            get {
                return ((string)(this["XWebIDDebit"]));
            }
            set {
                this["XWebIDDebit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FCChfQrLpCi429zQLvPh1OYbWaZFo56f")]
        public string XWebAuthKeyDebit {
            get {
                return ((string)(this["XWebAuthKeyDebit"]));
            }
            set {
                this["XWebAuthKeyDebit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80022803")]
        public string XWebTerminalIDDebit {
            get {
                return ((string)(this["XWebTerminalIDDebit"]));
            }
            set {
                this["XWebTerminalIDDebit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2082BF6DCE67560D318DEAF98C51AC64C2CF2F9E45B3C3F7E5A24B278CDE5FEA9859BE5FF80F0EAAC" +
            "5")]
        public string AccountToken {
            get {
                return ((string)(this["AccountToken"]));
            }
            set {
                this["AccountToken"] = value;
            }
        }
    }
}
