//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationsTester.VariableHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class EdgeLinkVariables : global::System.Configuration.ApplicationSettingsBase {
        
        private static EdgeLinkVariables defaultInstance = ((EdgeLinkVariables)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EdgeLinkVariables())));
        
        public static EdgeLinkVariables Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResultFileContent {
            get {
                return ((string)(this["ResultFileContent"]));
            }
            set {
                this["ResultFileContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResultFilePath {
            get {
                return ((string)(this["ResultFilePath"]));
            }
            set {
                this["ResultFilePath"] = value;
            }
        }
    }
}
