//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationsTester.VariableHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Globals : global::System.Configuration.ApplicationSettingsBase {
        
        private static Globals defaultInstance = ((Globals)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Globals())));
        
        public static Globals Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST")]
        public string Environment {
            get {
                return ((string)(this["Environment"]));
            }
            set {
                this["Environment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO_CHECK")]
        public string DuplicateMode {
            get {
                return ((string)(this["DuplicateMode"]));
            }
            set {
                this["DuplicateMode"] = value;
            }
        }
    }
}
