//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationsTester.VariableHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class LoopbackCredentials : global::System.Configuration.ApplicationSettingsBase {
        
        private static LoopbackCredentials defaultInstance = ((LoopbackCredentials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LoopbackCredentials())));
        
        public static LoopbackCredentials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebID {
            get {
                return ((string)(this["XWebID"]));
            }
            set {
                this["XWebID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebAuthKey {
            get {
                return ((string)(this["XWebAuthKey"]));
            }
            set {
                this["XWebAuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebTerminalID {
            get {
                return ((string)(this["XWebTerminalID"]));
            }
            set {
                this["XWebTerminalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountToken {
            get {
                return ((string)(this["AccountToken"]));
            }
            set {
                this["AccountToken"] = value;
            }
        }
    }
}
