//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationsTester.VariableHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class StandardCredentials : global::System.Configuration.ApplicationSettingsBase {
        
        private static StandardCredentials defaultInstance = ((StandardCredentials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StandardCredentials())));
        
        public static StandardCredentials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebID {
            get {
                return ((string)(this["XWebID"]));
            }
            set {
                this["XWebID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebAuthKey {
            get {
                return ((string)(this["XWebAuthKey"]));
            }
            set {
                this["XWebAuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XWebTerminalID {
            get {
                return ((string)(this["XWebTerminalID"]));
            }
            set {
                this["XWebTerminalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountToken {
            get {
                return ((string)(this["AccountToken"]));
            }
            set {
                this["AccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("account_token=C9CBE35FCE67540F328FE4FC8758AF6DCECC24954FB2C4FFE4A24F2B81D95FEA995" +
            "3BC5CF45601D078&transaction_type=CREDIT_CARD&entry_mode=KEYED&charge_type=SALE&c" +
            "harge_total=1&order_id=8370668886807390&duplicate_check=NO_CHECK&manage_payer_da" +
            "ta=true")]
        public string TestingString {
            get {
                return ((string)(this["TestingString"]));
            }
            set {
                this["TestingString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestTest")]
        public string ActiveAccountToken {
            get {
                return ((string)(this["ActiveAccountToken"]));
            }
            set {
                this["ActiveAccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveXWebID {
            get {
                return ((string)(this["ActiveXWebID"]));
            }
            set {
                this["ActiveXWebID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveXWebAuthKey {
            get {
                return ((string)(this["ActiveXWebAuthKey"]));
            }
            set {
                this["ActiveXWebAuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveXWebTerminalID {
            get {
                return ((string)(this["ActiveXWebTerminalID"]));
            }
            set {
                this["ActiveXWebTerminalID"] = value;
            }
        }
    }
}
